// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Beep():Promise<void>;

export function Reveal(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
