// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Beep():Promise<void>;

export function EnterText(arg1:string,arg2:string,arg3:string):Promise<string>;

export function OpenDirectory(arg1:string):Promise<string>;

export function Reveal(arg1:string):Promise<void>;

export function StartProgressBar(arg1:number,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopProgressBar(arg1:number):Promise<void>;
