// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Beep() {
  return window['go']['ui']['UI']['Beep']();
}

export function EnterText(arg1, arg2, arg3) {
  return window['go']['ui']['UI']['EnterText'](arg1, arg2, arg3);
}

export function OpenDirectory(arg1, arg2) {
  return window['go']['ui']['UI']['OpenDirectory'](arg1, arg2);
}

export function Reveal(arg1) {
  return window['go']['ui']['UI']['Reveal'](arg1);
}

export function Startup(arg1) {
  return window['go']['ui']['UI']['Startup'](arg1);
}
