// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Beep() {
  return window['go']['ui']['UI']['Beep']();
}

export function Reveal(arg1) {
  return window['go']['ui']['UI']['Reveal'](arg1);
}

export function Startup(arg1) {
  return window['go']['ui']['UI']['Startup'](arg1);
}
