blank_issues_enabled: false

contact_links:
  - name: Forums
    url: https://github.com/garraflavatra/rolens/discussions
    about: Do you have a question about Rolens? Please do not file an issue, but instead post your question here.
