name: Documentation issue
description: Report documentation issues here.
labels: [documentation]
assignees: [garraflavatra]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!

  - type: textarea
    id: source
    attributes:
      label: Source
      description: Which part of the documentation is erroneous? A link would be very nice!
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Why is it wrong?

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: What should the documentation say instead?
