// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {primitive} from '../models';
import {map[string]app} from '../models';
import {app} from '../models';

export function DropCollection(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function DropDatabase(arg1:string,arg2:string):Promise<boolean>;

export function GetIndexes(arg1:string,arg2:string,arg3:string):Promise<Array<primitive.M>>;

export function Hosts():Promise<map[string]app.Host>;

export function OpenCollection(arg1:string,arg2:string,arg3:string):Promise<primitive.M>;

export function OpenConnection(arg1:string):Promise<Array<string>>;

export function OpenDatabase(arg1:string,arg2:string):Promise<Array<string>>;

export function PerformFind(arg1:string,arg2:string,arg3:string,arg4:string):Promise<app.findResult>;

export function PerformInsert(arg1:string,arg2:string,arg3:string,arg4:string):Promise<any>;
