// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DropCollection(arg1, arg2, arg3) {
  return window['go']['app']['App']['DropCollection'](arg1, arg2, arg3);
}

export function DropDatabase(arg1, arg2) {
  return window['go']['app']['App']['DropDatabase'](arg1, arg2);
}

export function GetIndexes(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetIndexes'](arg1, arg2, arg3);
}

export function Hosts() {
  return window['go']['app']['App']['Hosts']();
}

export function OpenCollection(arg1, arg2, arg3) {
  return window['go']['app']['App']['OpenCollection'](arg1, arg2, arg3);
}

export function OpenConnection(arg1) {
  return window['go']['app']['App']['OpenConnection'](arg1);
}

export function OpenDatabase(arg1, arg2) {
  return window['go']['app']['App']['OpenDatabase'](arg1, arg2);
}

export function PerformFind(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['PerformFind'](arg1, arg2, arg3, arg4);
}

export function PerformInsert(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['PerformInsert'](arg1, arg2, arg3, arg4);
}
