// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHost(arg1) {
  return window['go']['app']['App']['AddHost'](arg1);
}

export function Aggregate(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['Aggregate'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateIndex(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateIndex'](arg1, arg2, arg3, arg4);
}

export function DropCollection(arg1, arg2, arg3) {
  return window['go']['app']['App']['DropCollection'](arg1, arg2, arg3);
}

export function DropDatabase(arg1, arg2) {
  return window['go']['app']['App']['DropDatabase'](arg1, arg2);
}

export function DropIndex(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DropIndex'](arg1, arg2, arg3, arg4);
}

export function Environment() {
  return window['go']['app']['App']['Environment']();
}

export function ExecuteShellScript(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExecuteShellScript'](arg1, arg2, arg3, arg4);
}

export function FindItems(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['FindItems'](arg1, arg2, arg3, arg4);
}

export function GetIndexes(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetIndexes'](arg1, arg2, arg3);
}

export function HostLogs(arg1, arg2) {
  return window['go']['app']['App']['HostLogs'](arg1, arg2);
}

export function Hosts() {
  return window['go']['app']['App']['Hosts']();
}

export function InsertItems(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['InsertItems'](arg1, arg2, arg3, arg4);
}

export function Menu() {
  return window['go']['app']['App']['Menu']();
}

export function OpenCollection(arg1, arg2, arg3) {
  return window['go']['app']['App']['OpenCollection'](arg1, arg2, arg3);
}

export function OpenConnection(arg1) {
  return window['go']['app']['App']['OpenConnection'](arg1);
}

export function OpenDatabase(arg1, arg2) {
  return window['go']['app']['App']['OpenDatabase'](arg1, arg2);
}

export function PerformDump(arg1) {
  return window['go']['app']['App']['PerformDump'](arg1);
}

export function PerformFindExport(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['PerformFindExport'](arg1, arg2, arg3, arg4);
}

export function PurgeLogDirectory() {
  return window['go']['app']['App']['PurgeLogDirectory']();
}

export function RemoveHost(arg1) {
  return window['go']['app']['App']['RemoveHost'](arg1);
}

export function RemoveItemById(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RemoveItemById'](arg1, arg2, arg3, arg4);
}

export function RemoveItems(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['RemoveItems'](arg1, arg2, arg3, arg4, arg5);
}

export function RemoveQuery(arg1) {
  return window['go']['app']['App']['RemoveQuery'](arg1);
}

export function RemoveView(arg1) {
  return window['go']['app']['App']['RemoveView'](arg1);
}

export function RenameCollection(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RenameCollection'](arg1, arg2, arg3, arg4);
}

export function ReportSharedStateVariable(arg1, arg2) {
  return window['go']['app']['App']['ReportSharedStateVariable'](arg1, arg2);
}

export function SaveQuery(arg1) {
  return window['go']['app']['App']['SaveQuery'](arg1);
}

export function SavedQueries() {
  return window['go']['app']['App']['SavedQueries']();
}

export function Settings() {
  return window['go']['app']['App']['Settings']();
}

export function Startup(arg1, arg2) {
  return window['go']['app']['App']['Startup'](arg1, arg2);
}

export function TruncateCollection(arg1, arg2, arg3) {
  return window['go']['app']['App']['TruncateCollection'](arg1, arg2, arg3);
}

export function UpdateFoundDocument(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['UpdateFoundDocument'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateHost(arg1, arg2) {
  return window['go']['app']['App']['UpdateHost'](arg1, arg2);
}

export function UpdateItems(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdateItems'](arg1, arg2, arg3, arg4);
}

export function UpdateQueries(arg1) {
  return window['go']['app']['App']['UpdateQueries'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}

export function UpdateViewStore(arg1) {
  return window['go']['app']['App']['UpdateViewStore'](arg1);
}

export function Views() {
  return window['go']['app']['App']['Views']();
}
