// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHost(arg1) {
  return window['go']['app']['App']['AddHost'](arg1);
}

export function CreateIndex(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateIndex'](arg1, arg2, arg3, arg4);
}

export function DropCollection(arg1, arg2, arg3) {
  return window['go']['app']['App']['DropCollection'](arg1, arg2, arg3);
}

export function DropDatabase(arg1, arg2) {
  return window['go']['app']['App']['DropDatabase'](arg1, arg2);
}

export function DropIndex(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DropIndex'](arg1, arg2, arg3, arg4);
}

export function FindItems(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['FindItems'](arg1, arg2, arg3, arg4);
}

export function GetIndexes(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetIndexes'](arg1, arg2, arg3);
}

export function Hosts() {
  return window['go']['app']['App']['Hosts']();
}

export function InsertItems(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['InsertItems'](arg1, arg2, arg3, arg4);
}

export function Menu() {
  return window['go']['app']['App']['Menu']();
}

export function OpenCollection(arg1, arg2, arg3) {
  return window['go']['app']['App']['OpenCollection'](arg1, arg2, arg3);
}

export function OpenConnection(arg1) {
  return window['go']['app']['App']['OpenConnection'](arg1);
}

export function OpenDatabase(arg1, arg2) {
  return window['go']['app']['App']['OpenDatabase'](arg1, arg2);
}

export function RemoveHost(arg1) {
  return window['go']['app']['App']['RemoveHost'](arg1);
}

export function RemoveItemById(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RemoveItemById'](arg1, arg2, arg3, arg4);
}

export function RemoveItems(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['RemoveItems'](arg1, arg2, arg3, arg4, arg5);
}

export function Settings() {
  return window['go']['app']['App']['Settings']();
}

export function UpdateHost(arg1, arg2) {
  return window['go']['app']['App']['UpdateHost'](arg1, arg2);
}

export function UpdateItems(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdateItems'](arg1, arg2, arg3, arg4);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}
