name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Rolens

    strategy:
      fail-fast: false
      matrix:
        platform: [windows-2022, macos-12, ubuntu-22.04]
        go-version: [1.18]
        node-version: [16]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        cache-dependency-path: go.sum

    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Install Wails dependencies for Linux
      if: matrix.platform == 'ubuntu-22.04'
      run: sudo apt-get install gtk+-3.0 webkit2gtk-4.0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
        cache-dependency-path: frontend/package-lock.json

    - name: Cross-compile Rolens for Windows
      if: matrix.platform == 'windows-2022'
      run: |
        mkdir releases
        wails build -platform windows/amd64
        tar -czvf releases\rolens-windows-10+-amd64.tar.gz --directory build\bin Rolens.exe
        "tar_amd64=rolens-windows-10+-amd64.tar.gz" >> $env:GITHUB_ENV
        rmdir /s ".\build\bin"
        wails build -platform windows/arm64
        tar -czvf releases\rolens-windows-10+-arm64.tar.gz --directory build\bin Rolens.exe
        "tar_amd64=rolens-windows-10+-arm64.tar.gz" >> $env:GITHUB_ENV

    - name: Cross-compile Rolens for Darwin
      if: matrix.platform == 'macos-12'
      run: |
        mkdir releases
        wails build -platform darwin/amd64
        tar -czvf releases/rolens-macos-10.13+-amd64.tar.gz --directory build/bin Rolens.app
        echo "tar_amd64=rolens-macos-10.13+-amd64.tar.gz" >> "$GITHUB_ENV"
        rm -rf build/bin
        wails build -platform darwin/arm64
        tar -czvf releases/rolens-11.0+-arm64.tar.gz --directory build/bin Rolens.app
        echo "tar_amd64=rolens-11.0+-arm64.tar.gz" >> "$GITHUB_ENV"

    - name: Cross-compile Rolens for Linux
      if: matrix.platform == 'ubuntu-22.04'
      run: |
        mkdir releases
        wails build -platform linux/amd64
        tar -czvf releases/rolens-linux-amd64.tar.gz --directory build/bin Rolens
        echo "tar_amd64=rolens-linux-amd64.tar.gz" >> "$GITHUB_ENV"
        # rm -rf build/bin
        # wails build -platform linux/arm64
        # tar -czvf releases/rolens-linux-arm64.tar.gz --directory build/bin Rolens
        # echo "tar_arm64=rolens-linux-arm64.tar.gz" >> "$GITHUB_ENV"

    - name: Upload generated amd64 binary
      if: env.tar_amd64
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.tar_amd64 }}
        path: releases/${{ env.tar_amd64 }}

    - name: Upload generated arm64 binary
      if: env.rat_arm64
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.tar_arm64 }}
        path: releases/${{ env.tar_arm64 }}
